# Generated by Django 5.2 on 2025-07-07 04:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptionTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('preparation', '事前準備'), ('application', '申請書作成'), ('documents', '必要書類'), ('strategy', '戦略・ポイント'), ('common_mistakes', 'よくある失敗'), ('success_factors', '成功要因')], max_length=50, verbose_name='カテゴリ')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('importance', models.IntegerField(choices=[(1, '低'), (2, '中'), (3, '高'), (4, '最重要')], default=2, verbose_name='重要度')),
                ('effective_timing', models.CharField(blank=True, max_length=100, verbose_name='効果的な時期')),
                ('reference_url', models.URLField(blank=True, verbose_name='参考URL')),
                ('is_success_case', models.BooleanField(default=False, verbose_name='成功事例')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsidy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_tips', to='advisor.subsidytype')),
            ],
            options={
                'verbose_name': '採択ティップス',
                'verbose_name_plural': '採択ティップス',
                'ordering': ['-importance', 'category'],
            },
        ),
        migrations.CreateModel(
            name='UserApplicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(verbose_name='申請日')),
                ('application_round', models.IntegerField(default=1, verbose_name='申請回次')),
                ('status', models.CharField(choices=[('preparing', '準備中'), ('submitted', '申請済み'), ('under_review', '審査中'), ('adopted', '採択'), ('rejected', '不採択'), ('withdrawn', '取り下げ')], default='preparing', max_length=20, verbose_name='ステータス')),
                ('result_date', models.DateField(blank=True, null=True, verbose_name='結果発表日')),
                ('feedback', models.TextField(blank=True, verbose_name='フィードバック・コメント')),
                ('business_type_at_application', models.CharField(max_length=100, verbose_name='申請時事業種別')),
                ('company_size_at_application', models.CharField(max_length=50, verbose_name='申請時企業規模')),
                ('requested_amount', models.IntegerField(blank=True, null=True, verbose_name='申請金額')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsidy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.subsidytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '申請履歴',
                'verbose_name_plural': '申請履歴',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='AdoptionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('round_number', models.IntegerField(default=1, verbose_name='回次')),
                ('total_applications', models.IntegerField(verbose_name='総申請数')),
                ('total_adoptions', models.IntegerField(verbose_name='総採択数')),
                ('adoption_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='採択率')),
                ('small_business_applications', models.IntegerField(default=0, verbose_name='小規模事業者申請数')),
                ('small_business_adoptions', models.IntegerField(default=0, verbose_name='小規模事業者採択数')),
                ('medium_business_applications', models.IntegerField(default=0, verbose_name='中小企業申請数')),
                ('medium_business_adoptions', models.IntegerField(default=0, verbose_name='中小企業採択数')),
                ('industry_statistics', models.JSONField(blank=True, default=dict, verbose_name='業種別統計')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsidy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='advisor.subsidytype')),
            ],
            options={
                'verbose_name': '採択統計',
                'verbose_name_plural': '採択統計',
                'ordering': ['-year', '-round_number'],
                'unique_together': {('subsidy_type', 'year', 'round_number')},
            },
        ),
        migrations.CreateModel(
            name='ApplicationScoreCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_plan_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='事業計画スコア')),
                ('innovation_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='革新性スコア')),
                ('feasibility_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='実現可能性スコア')),
                ('market_potential_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='市場性スコア')),
                ('financial_health_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='財務健全性スコア')),
                ('total_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='総合スコア')),
                ('improvement_suggestions', models.JSONField(default=list, verbose_name='改善提案')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subsidy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.subsidytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '採択スコアカード',
                'verbose_name_plural': '採択スコアカード',
                'unique_together': {('user', 'subsidy_type')},
            },
        ),
    ]
