# Generated by Django 5.2 on 2025-07-11 05:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_adoptiontips_userapplicationhistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubsidyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_year', models.IntegerField(verbose_name='予測年度')),
                ('predicted_round', models.IntegerField(default=1, verbose_name='予測回次')),
                ('predicted_start_date', models.DateField(verbose_name='予測開始日')),
                ('predicted_end_date', models.DateField(verbose_name='予測締切日')),
                ('predicted_announcement_date', models.DateField(blank=True, null=True, verbose_name='予測発表日')),
                ('prediction_basis', models.CharField(choices=[('historical', '過去実績'), ('official_announcement', '公式発表'), ('budget_cycle', '予算サイクル'), ('policy_change', '政策変更'), ('trend_analysis', 'トレンド分析')], default='historical', max_length=30, verbose_name='予測根拠')),
                ('confidence_score', models.IntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='信頼度スコア')),
                ('probability_percentage', models.FloatField(default=80.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='実施確率')),
                ('prediction_notes', models.TextField(blank=True, verbose_name='予測詳細')),
                ('risk_factors', models.TextField(blank=True, verbose_name='リスク要因')),
                ('historical_data_years', models.IntegerField(default=3, verbose_name='参考年数')),
                ('last_year_date', models.DateField(blank=True, null=True, verbose_name='昨年実施日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsidy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='advisor.subsidytype')),
            ],
            options={
                'verbose_name': '補助金予測',
                'verbose_name_plural': '補助金予測',
                'ordering': ['predicted_start_date'],
                'unique_together': {('subsidy_type', 'predicted_year', 'predicted_round')},
            },
        ),
        migrations.CreateModel(
            name='SubsidySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('round_number', models.IntegerField(default=1, verbose_name='公募回次')),
                ('application_start_date', models.DateField(verbose_name='申請開始日')),
                ('application_end_date', models.DateField(verbose_name='申請締切日')),
                ('result_announcement_date', models.DateField(blank=True, null=True, verbose_name='結果発表予定日')),
                ('project_start_date', models.DateField(blank=True, null=True, verbose_name='事業開始日')),
                ('project_end_date', models.DateField(blank=True, null=True, verbose_name='事業終了日')),
                ('total_budget', models.BigIntegerField(blank=True, null=True, verbose_name='総予算額')),
                ('allocated_budget', models.BigIntegerField(blank=True, null=True, verbose_name='配分予算額')),
                ('status', models.CharField(choices=[('scheduled', '予定'), ('active', '公募中'), ('closed', '締切済み'), ('completed', '完了'), ('cancelled', '中止')], default='scheduled', max_length=20, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('is_prediction', models.BooleanField(default=False, verbose_name='予測データ')),
                ('confidence_level', models.IntegerField(default=50, help_text='予測の信頼度（0-100%）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='予測信頼度')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subsidy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='advisor.subsidytype')),
            ],
            options={
                'verbose_name': '補助金スケジュール',
                'verbose_name_plural': '補助金スケジュール',
                'ordering': ['year', 'application_start_date', 'round_number'],
                'unique_together': {('subsidy_type', 'year', 'round_number')},
            },
        ),
    ]
