# Generated by Django 5.2 on 2025-07-15 01:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0003_subsidyprediction_subsidyschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_date', models.DateField(verbose_name='分析日')),
                ('seasonal_patterns', models.JSONField(default=dict, verbose_name='季節パターン')),
                ('budget_trends', models.JSONField(default=dict, verbose_name='予算トレンド')),
                ('competition_analysis', models.JSONField(default=dict, verbose_name='競合分析')),
                ('success_rate_trends', models.JSONField(default=dict, verbose_name='成功率トレンド')),
                ('emerging_opportunities', models.JSONField(default=list, verbose_name='新たな機会')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'トレンド分析',
                'verbose_name_plural': 'トレンド分析',
                'ordering': ['-analysis_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='conversationhistory',
            options={'ordering': ['-timestamp'], 'verbose_name': '会話履歴', 'verbose_name_plural': '会話履歴'},
        ),
        migrations.AlterModelOptions(
            name='subsidyprediction',
            options={'ordering': ['predicted_date'], 'verbose_name': '補助金予測', 'verbose_name_plural': '補助金予測'},
        ),
        migrations.AlterUniqueTogether(
            name='subsidyprediction',
            unique_together={('subsidy_type', 'predicted_date')},
        ),
        migrations.RemoveField(
            model_name='subsidytype',
            name='application_period',
        ),
        migrations.RemoveField(
            model_name='subsidytype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subsidytype',
            name='subsidy_rate',
        ),
        migrations.RemoveField(
            model_name='subsidytype',
            name='target_business',
        ),
        migrations.RemoveField(
            model_name='subsidytype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='intent_analysis',
            field=models.JSONField(default=dict, verbose_name='意図分析結果'),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='metadata',
            field=models.JSONField(default=dict, help_text='信頼度、推奨補助金、使用モデル等', verbose_name='メタデータ'),
        ),
        migrations.AddField(
            model_name='conversationhistory',
            name='user_context',
            field=models.JSONField(default=dict, verbose_name='ユーザーコンテキスト'),
        ),
        migrations.AddField(
            model_name='subsidyprediction',
            name='estimated_budget',
            field=models.IntegerField(blank=True, null=True, verbose_name='予測予算（万円）'),
        ),
        migrations.AddField(
            model_name='subsidyprediction',
            name='model_version',
            field=models.CharField(default='v1.0', max_length=50, verbose_name='予測モデルバージョン'),
        ),
        migrations.AddField(
            model_name='subsidyprediction',
            name='predicted_date',
            field=models.DateField(default=datetime.date(2025, 7, 15), verbose_name='予測公募日'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyprediction',
            name='preparation_deadline',
            field=models.DateField(default=datetime.date(2025, 7, 15), verbose_name='準備期限'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidyprediction',
            name='recommendation_priority',
            field=models.FloatField(default=0.5, verbose_name='推奨優先度'),
        ),
        migrations.AddField(
            model_name='subsidyprediction',
            name='success_probability',
            field=models.FloatField(default=0.25, verbose_name='成功確率'),
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='application_difficulty',
            field=models.IntegerField(choices=[(1, 'レベル1'), (2, 'レベル2'), (3, 'レベル3'), (4, 'レベル4'), (5, 'レベル5')], default=3, verbose_name='申請難易度（1-5）'),
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='average_preparation_weeks',
            field=models.IntegerField(default=8, verbose_name='平均準備期間（週）'),
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='historical_success_rate',
            field=models.FloatField(default=0.25, verbose_name='過去の成功率'),
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='アクティブ'),
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新'),
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='target_business_type',
            field=models.CharField(default=datetime.date(2025, 7, 15), max_length=255, verbose_name='対象事業種別'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subsidytype',
            name='typical_application_months',
            field=models.JSONField(default=list, help_text='例: [1, 4, 7, 10]', verbose_name='通常の申請月'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='content',
            field=models.TextField(verbose_name='メッセージ内容'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='message_type',
            field=models.CharField(choices=[('user', 'ユーザー'), ('assistant', 'アシスタント'), ('system', 'システム')], max_length=20, verbose_name='メッセージ種別'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='session_id',
            field=models.CharField(max_length=255, verbose_name='セッションID'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='タイムスタンプ'),
        ),
        migrations.AlterField(
            model_name='conversationhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='subsidyprediction',
            name='confidence_score',
            field=models.FloatField(help_text='0.0-1.0の範囲', verbose_name='信頼度スコア'),
        ),
        migrations.AlterField(
            model_name='subsidyprediction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='subsidyprediction',
            name='prediction_basis',
            field=models.JSONField(default=dict, help_text='季節性、過去実績等の分析結果', verbose_name='予測根拠'),
        ),
        migrations.AlterField(
            model_name='subsidyprediction',
            name='subsidy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advisor.subsidytype', verbose_name='補助金種別'),
        ),
        migrations.AlterField(
            model_name='subsidytype',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='subsidytype',
            name='max_amount',
            field=models.IntegerField(verbose_name='最大金額（万円）'),
        ),
        migrations.AlterField(
            model_name='subsidytype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='補助金名'),
        ),
        migrations.CreateModel(
            name='UserAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('preparation_deadline', '準備期限'), ('high_opportunity', '高確率案件'), ('new_subsidy', '新規補助金'), ('trend_change', 'トレンド変化')], max_length=50, verbose_name='アラート種別')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=20, verbose_name='優先度')),
                ('action_required', models.TextField(blank=True, null=True, verbose_name='必要なアクション')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('is_dismissed', models.BooleanField(default=False, verbose_name='非表示')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('related_subsidy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advisor.subsidytype', verbose_name='関連補助金')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ユーザーアラート',
                'verbose_name_plural': 'ユーザーアラート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='historical_data_years',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='last_year_date',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='predicted_announcement_date',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='predicted_end_date',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='predicted_round',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='predicted_start_date',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='predicted_year',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='prediction_notes',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='probability_percentage',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='risk_factors',
        ),
        migrations.RemoveField(
            model_name='subsidyprediction',
            name='updated_at',
        ),
    ]
